### PR TITLE
Tests are slow, so I only left Debian os

### PR DESCRIPTION
**Pull request by melezhik**
Also I use `-to=home` to address issue when tested against various rakudo versions ( the issue is not presented here, however this is a _general_ problem  ).

### CODE REVIEW

**Comment by melezhik** [comment]
I have an interesting effect, when using `zef install -to=home` Rakudo that is tested first has way more faster time , then the following one, irrespectively on version ... 

Here, 2022.07 is tested first [report](https://ci.sparrowhub.io/report/1985):

```
21:27:59 :: O----------------O--------O-----------------------------------------------------------O------------O
21:27:59 :: | Rakudo Version | Status | Time                                                      | Linux Dist |
21:27:59 :: O================O========O===========================================================O============O
21:27:59 :: | 2022.07        | OK     | 1:26.51 real,129.52 user,7.70 sys / CPU Percentage: 158%  | debian     |
21:27:59 :: | 2022.06        | OK     | 3:55.38 real,353.37 user,23.51 sys / CPU Percentage: 160% | debian     |
21:27:59 :: ----------------------------------------------------------------------------------------------------
```

Here, Rakudo 2022.06 is tested first [report](https://ci.sparrowhub.io/report/1983):

```
20:47:00 :: O----------------O--------O-----------------------------------------------------------O------------O
20:47:00 :: | Rakudo Version | Status | Time                                                      | Linux Dist |
20:47:00 :: O================O========O===========================================================O============O
20:47:00 :: | 2022.06        | OK     | 1:30.74 real,133.11 user,8.00 sys / CPU Percentage: 155%  | debian     |
20:47:00 :: | 2022.07        | OK     | 4:04.41 real,369.63 user,24.25 sys / CPU Percentage: 161% | debian     |
20:47:00 :: ----------------------------------------------------------------------------------------------------
```

so 1 min VS 4 min is significant difference, a I don't know why this happens, maybe because when we run tests for the second _whatever_ rakudo versions , cache (`~/.raku`) from the first Rakudo installation somehow affects the second Rakudo tests?

**Comment by melezhik** [comment]
also worth to mention that 4 minutes for tests is way too much ... 🤔

**Comment by melezhik** [comment]
is it even legit way to install into home (-to=home) and reuse the same files (`~/.raku`) across different rakudos ?
cc @ugexe

**Comment by dwarring** [comment]
Worth noting that It's the precompilation overheads that are the bottleneck, not the tests themselves..

On a second run,  `zef test .` takes about 30sec on my modest debian x86 i7 PC. `prove6 -I. -j4` about 12sec.

**Comment by melezhik** [comment]
@dwarring the point I am trying to make here - that the tests that runs _second time_ are always slower irrespectively on rakudo version, which is weird, as following the logic pre-compilation  already happened (drying the first tests run) and the second tests run should be faster at this point, what I see is quite opposite ...

**Pull request merged**
